name: proyecto_meteorologico
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - python-dotenv
    - numpy
    - pandas
    - fastapi
    - uvicorn
    - streamlit
    - aiohttp
    - requests
    - sqlalchemy
    - psycopg2
    - asyncpg