DEV = true
HOST = "localhost"

[database]
DB_USER = "postgres.rednvrsdcuwtwyfxtjru"
DB_PASSWORD = "hackaboss123"
DB_HOST = "aws-0-eu-west-2.pooler.supabase.com"
DB_PORT = 6543
DB_NAME = "postgres"

[api]
API_HOST = "localhost"
API_PORT = 8000

[streamlit]
STREAMLIT_HOST = "localhost"
STREAMLIT_PORT = 8501

[aemet]
AEMET_API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjbGF1ZGlhdG9ydmlzb0BnbWFpbC5jb20iLCJqdGkiOiI2MTU1ZDI5NS01NmUyLTQ5YjMtYmFhYi0xMzNhYmRhZjE5NjgiLCJpc3MiOiJBRU1FVCIsImlhdCI6MTczODk1MjE5MywidXNlcklkIjoiNjE1NWQyOTUtNTZlMi00OWIzLWJhYWItMTMzYWJkYWYxOTY4Iiwicm9sZSI6IiJ9.85ehsuEa591KaqVnIewrCI4QSnE3NsJlm5UyP87h1Ho"
