name: Setup .env file

on: [push, pull_request]

jobs:
  setup-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "AEMET_API_KEY=${{ secrets.AEMET_API_KEY }}" > .env
          grep "AEMET_API_KEY" .env | cut -d '=' -f2 | cut -c1-5

      - name: Use the .env file
        run: |
          source .env
          echo "AEMET API Key Loaded"
