name: Register Streamlit Deployment

on:
  push:
    branches:
      - main

jobs:
  register-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Register Deployment
        uses: chrnorm/deployment-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: "Streamlit Cloud"
          description: "Deployed to Streamlit Cloud"
          log-url: "https://proyectometeorologico.streamlit.app"
